### PR TITLE
Improve shortcuts

### PR DESCRIPTION
**Pull request by nicknikolov**
- cmd+shift+o for opening new graph
- cmd+shift+c for cloning it

I sniff platform and replace cmd with ctrl for windows.
I also hid copy and paste buttons for now as document.execCommand('copy/paste') is tricky so only keyboard support for now.

### CODE REVIEW

**Comment by vorg** [comment]
execCommand works in safari under the following conditions:
- it's fired on user initiated event like mouse
- a selection exists

Example code based on: https://bugs.webkit.org/show_bug.cgi?id=156529

```javascript
function bogusSelect() {
  var sel = document.getSelection();
  // If "nothing" is selected...
  if (!document.queryCommandEnabled("copy") && sel.isCollapsed) {
    // ... temporarily select the entire body.
    //
    // We select the entire body because:
    // - its guaranteed to exist,
    // - it works (unlike, say, document.head, or phantom element that is
    //   not inserted into the DOM),
    // - it doesnt seem to flicker (due to the synchronous copy event), and
    // - it avoids modifying the DOM (can trigger mutation observers).
    //
    // Because we cant do proper feature detection (we already checked
    // document.queryCommandEnabled("copy") , which actually gives a false
    // negative for Blink when nothing is selected) and UA sniffing is not
    // reliable (a lot of UA strings contain "Safari"), this will also
    // happen for some browsers other than Safari. :-()
    var range = document.createRange();
    range.selectNodeContents(document.body);
    sel.addRange(range);
    _bogusSelection = true;
 }

function handler (e) {
  console.log('copy', e.clipboardData)
  e.clipboardData.setData('text/plain', 'bla : ' + new Date())
  e.preventDefault()
}
document.body.addEventListener('copy', handler)
document.body.addEventListener('click', () => {
  console.log('click')
  bogusSelect()
  document.execCommand('copy')
  document.getSelection().empty()
})
document.body.addEventListener('keypress', () => {
  console.log('keypress')
  bogusSelect()
  document.execCommand('copy')
  document.getSelection().empty()
})
```

**Comment by vorg** [comment]
We decided to:
- merge NodePicker with SearchModal
- we move all shortcuts to keyboard file
- graph handles file open/save events
- search modal handles up/down key events

**Comment by nicknikolov** [comment]
OK so:
1. Removed:
commands/ScrollDown.js
commands/ScrollUp.js
commands/SelectNodeDown.js
commands/SelectNodeLeft.js
commands/SelectNodeRight.js
commands/SelectNodeUp.js

These are just events in graph now.

2. Check out new config file:
https://github.com/pex-gl/pex-nodes/pull/226/files#diff-5e6c5b7525f012cb2969be12c34cc2b9

3. Commands are handled from graph-editor so i can inject graph.

Needs some nice testing this one...
If you can play around with it a bit this weekend + provide suggestion for keybindings would be good.

**Comment by nicknikolov** [comment]
TODO
- [ ] node picker

**Pull request merged**
