### PR TITLE
Choo layout

### PR DESCRIPTION
**Pull request by vorg**
Flexbox FTW!

Feedback needed:
- changeLayout event naming and params
- where to store current layout (currently state.project.layout)
- how to avoid delayed window.dispatchEvent(new Event('resize')) on on('graph:changeLayout') in GraphEditor and on('shell:fullscreen') in Shell. I need to do that because first render will update containers and layout and we need to fire resize a bit later so the scene can adapt.

### CODE REVIEW

**Comment by nicknikolov** [comment]
This still happens:
screen shot 2018-02-07 at 14 29 06

**Comment by nicknikolov** [comment]
Also lots of leaking happening:
screen shot 2018-02-07 at 14 34 30

**Comment by nicknikolov** [comment]
screen shot 2018-02-07 at 14 36 06

**Comment by vorg** [comment]
Fixed elements leaking with position:relative and overflow:hidden. Can you recreate that canvas dropping below scene (second screenshot)?

**Comment by nicknikolov** [comment]
Seems fixed, nice.

When I toggle fullscreen I'm getting some errors:
screen shot 2018-02-07 at 17 24 34

**Pull request merged**
