### PR TITLE
Bright theme 2

### PR DESCRIPTION
**Pull request by nicknikolov**

### CODE REVIEW

**Comment by nicknikolov** [comment]
screen shot 2018-04-27 at 16 40 42

**Comment by vorg** [comment]
We need proper color controls for comments https://github.com/pex-gl/pex-nodes/issues/276

**Comment by vorg** [comment]
Brighter bg color? e.g. #F5F5F5  screen shot 2018-04-30 at 12 12 59

**Comment by vorg** [comment]
To sum up our call, what i think is needed to merge this PR:
- test if dark theme works, especially ui styling
- brighter bg?

Extras:
- basic user settings UI (could be just textarea with json)
- proper color picker for comment colors

**Pull request merged**
